<div class="tm-overlay-05 tm-our-process-bg"></div>
<header class="container">
    <div class="tm-sect-06">
        <h1 class="text-center tm-text-line-normal"><strong>Terms and Conditions</strong></h1>
    </div>
</header>
</div>
<main>
    <section class="tm-bg-01 tm-sect-01">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-push-2">
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">By placing an order with <strong>MakeSocial</strong>, you confirm that you are in agreement with and bound by the terms and conditions below.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Definitions:</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The Client: The company or individual requesting the services of MakeSocial.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15"><strong>MakeSocial</strong>: Primary designer/site owner & employees or affiliates.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>General</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will carry out work only where an agreement is provided either by email, telephone, mail or fax. MakeSocial will carry out work only for clients who are 18 years of age or above. An ‘order’ is deemed to be a written or verbal contract between MakeSocial and the client, this includes telephone and email agreements.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Website Design</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Whilst every endeavor will be made to ensure that the website and any scripts or programs are free of errors, MakeSocial cannot accept responsibility for any losses incurred due to malfunction, the website or any part of it.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The website, graphics and any programming code remain the property of MakeSocial until all outstanding accounts are paid in full.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Any scripts, cgi applications, php scripts, or software (unless specifically agreed) written by MakeSocial remain the copyright of MakeSocial and may only be commercially reproduced or resold with the permission of MakeSocial.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial cannot take responsibility for any copyright infringements caused by materials submitted by the client. We reserve the right to refuse any material of a copyrighted nature unless adequate proof is given of permission to use such material.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Any additions to the brief will be carried out at the discretion of MakeSocial and where no charge is made by MakeSocial for such additions, MakeSocial accept no responsibility to ensure such additions are error free and reserve the right to charge an according amount for any correction to these or further additions.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The client agrees to make available as soon as is reasonably possible to MakeSocial all materials required to complete the site to the agreed standard and within the set deadline.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will not be liable for costs incurred, compensation or loss of earnings due to the failure to meet agreed deadlines.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will not be liable or become involved in any disputes between the site owner and their clients and cannot be held responsible for any wrongdoing on the part of a site owner.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will not be liable for any costs incurred, compensation or loss of earnings due to the work carried out on behalf of the client or any of the clients appointed agents.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will not be liable for any costs incurred, compensation or loss of earnings due to the unavailability of the site, its servers, software or any material provided by its agents.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">A deposit of 50% is required with any project before any design work will be carried out.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Once a website has been designed and completed the final balance of payment is then due in accordance with our payment terms. There are no exceptions to this, i.e If the client decides they no longer want the site, as they have commissioned the work and paid a deposit they are still obliged to pay for the work that has been done. Non payment will result in legal action being taken if necessary.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Database, Application and E-Commerce Development</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial cannot take responsibility for any losses incurred by the use of any software created for the client. Whilst every care has been taken to ensure products are problem free and accurate, the ultimate responsibility lies with the client in ensuring that all software is functioning correctly before use.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Any scripts, cgi applications or software (unless specifically agreed) written by MakeSocial remain the copyright of MakeSocial and may only be commercially reproduced or resold with the permission of MakeSocial.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Where applications or sites are developed on servers not recommended by MakeSocial, the client is expected to provide or seek any information,additional software,support or co-operation pertaining to the server required in order for the application to be correctly developed. Where large applications are to be developed, it is the clients responsibility to provide a suitable testing environment which is identical to the final production environment.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The client is expected to test fully any application or programming relating to a site developed by MakeSocial before being made generally available for use. Where “bugs”, errors or other issues are found after the site is live, MakeSocial will endeavor (but is not obliged to) to correct these issues to meet the standards of function outlined in the brief.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Website Hosting</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">We offer limited hosting services by buying server space from Amazon Web Services. They have great customer and technical support and service guarantee for an annual average of 99% network availability for their infrastructure. Should you require any additional information, please refer to the AWS' own websites for their <a class="tm-a-transition" href="https://aws.amazon.com/terms/?nc1=f_pr" target="_blank">site terms</a>.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Payment of Accounts</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">A deposit is required from any new client before any work is carried out. It is the MakeSocial policy that any outstanding accounts for work carried out by MakeSocial or its affiliates are required to be paid in full, no later than 30 days from the date of the invoice unless by prior arrangement with MakeSocial.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Once a deposit is paid and work completed you are obliged to pay the balance of payment in full. We will contact clients via email and telephone to remind them of such payments if they are not received when due.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">If accounts are not settled or MakeSocial have not been contacted regarding the delay, access to the related website may be denied and web pages removed, we will then pass such cases to the Small Claims Court to pursue payment, non payment can result in county court judgements (ccj’s) being added to the clients credit rating.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Following consistent non payment of an invoice our Solicitors will contact the client in question, with a view to taking the matter further and if need be to seek payment through legal procedures, and if necessary court summons.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Passing of Rights</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Once all amounts due to us from you are paid and cleared you are assigned the rights to use, as applicable, the products and services, including, the web site which includes the text, graphics, animation, audio components and digital components contained within the finished web site, in accordance with these terms and conditions, the Project Agreement and any applicable agreement, terms or licence but no rights of ownership are conveyed unless specifically stated in the Project Contract.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">No such rights as described in above will pass until all amounts due to us from you are paid. This means that we will have a lien over any service, products, data or information. If you have not paid the invoice in full within 2 months from the date of the invoice you agree that you will forfeit your rights.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The rights to photographs, graphics and any third party items such as source code, always remain the property of their respective owners.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Unless you have our specific written agreement in the Project Contract, all products, including Content Management Systems, interfaces, navigational devices, menus, menu structures or arrangements, icons, help, all operational instructions, scripts, cgi applications, software, programming/source code, and all other components of any source or object computer code that comprises the Website, all literal and non-literal expressions of ideas that operate, cause, create, direct, manipulate, access, or otherwise affect the Content and design elements used or developed and all software, and our products and results of our services remain our property and we retain full ownership rights and all intellectual property rights. You specifically agree not do anything that may in any way infringe upon or undermine our rights, title, or interest in the Website or our products and services. This includes, but is not limited to, any sale, transfer or gift of the whole or of any part of any item, data or anything whatsoever that we own. You fully understand that we may reproduce, reuse, develop and use in any other way we choose, anything within our ownership.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Complaints Procedure</strong></h3>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Informal procedure</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">Anyone who experiences a problem with their web service provided by MakeSocial should raise the matter directly using our online contact form to do so, giving sufficient information to locate the material (such as an url) and clearly outlining the grounds for complaint.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">MakeSocial will approach the individual responsible for the material in question with a view to resolving the matter to the satisfaction of the complainant.</p>
                    <h3 class="tm-margin-01 tm-text-line-normal"><strong>Formal complaints procedure</strong></h3>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">The formal complaints procedure should only be used where the complainant feels that the nature of the complaint is too serious to be dealt with informally, or where a satisfactory conclusion has not been reached after following the informal procedure.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">A formal complaint should be made in writing to MakeSocial, who will acknowledge receipt and ensure that the matter is looked into as soon as possible.</p>
                    <p class="tm-default-p tm-margin-01 tm-text-line-15">An initial response to any complaint can be expected within seven days of its receipt; a full and considered response to the complaint should be completed within 30 days and any subsequent remedy implemented with the minimum of delay.</p>
                </div>
            </div>
        </div>
    </section>